crawler:
  start_urls:
  
  - "https://www.votresante.bf/"
  



  headers:
    User-Agent: "SpiderBot/1.0 (+https://github.com/ScrApErxeb/Spider)"
    Accept-Language: "en,fr,es,zh,de,ar,pt,hi,ru,ja"
  
  
  timeout: 50
  retries: 3
  max_pages: 1000
  robots: false
  rate_limit_per_domain: 2
  verify_ssl: false

http_cache:
  enabled: true
  ttl: 300

allowed_langs: ["en", "fr"]

rate_limit_enabled: true

storage:
  database_path: "data/project.db"
  export_dir: "exports"

logging:
  level: "INFO"
  file: "logs/pipeline.log"



salut:
  - "https://ouagabuzz.com/"
  - "https://maliweb.net/"
  - "https://mali24.info/"
  - "https://maliactu.net/"
  - "https://askia24.net/"
  - "https://maliactualites.com/"
  - "https://www.journalduniger.com/"
  - "https://www.infos-niger.com/"
  - "https://www.nigerinfos.com/"
  - "https://nigerfocus.com/"
  - "https://www.nigerdiaspora.net/"
  - "https://lefaso.net/"
  - "https://www.burkina24.com/"
